name: Deploy to GitHubPages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  chek-linting:
    name: Check Linting
    needs: build-data
    permissions:
      contents: read
    uses: ./.github/workflows/lint.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [chek-linting]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Install dependencies
        run: deno install

      - name: Build project
        run: deno task build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
